import { Relation } from './types'

export const sample: Relation[] = [
  {
    id: 'id_1',
    name: 'John',
    surname: 'Doe',
    gender: 'male',
    age: 34,
    phone: '020-2354-393',
    email: 'john.doe@example.com',
    address: 'Zekeringsstraat 32, Amsterdam',
  },
  {
    id: 'id_2',
    name: 'Jane',
    surname: 'Smith',
    gender: 'female',
    age: 29,
    phone: '2345-7891',
    email: 'jane.smith@example.com',
    address: '456 Elm St',
  },
  {
    id: 'id_3',
    name: 'Alex',
    surname: 'Johnson',
    gender: 'other',
    age: 41,
    phone: '12-456-7892',
    email: 'alex.johnson@example.com',
    address: '789 Oak St',
  },
  {
    id: 'id_4',
    name: 'Emily',
    surname: 'Williams',
    gender: 'female',
    age: 25,
    phone: '123-45-7893',
    email: 'emily.williams@example.com',
    address: '159 Maple St',
  },
  {
    id: 'id_5',
    name: 'Chris',
    surname: 'Taylor',
    gender: 'male',
    age: 55,
    phone: '123-456-794',
    email: 'chris.taylor@example.com',
    address: '753 Pine St',
  },
  {
    id: 'id_6',
    name: 'Rachel',
    surname: 'Brown',
    gender: 'female',
    age: 21,
    phone: '123-456-7895',
    email: 'rachel.brown@example.com',
    address: '951 Birch St',
  },
  {
    id: 'id_7',
    name: 'Michael',
    surname: 'Clark',
    gender: 'male',
    age: 48,
    phone: '123-456-7896',
    email: 'michael.clark@example.com',
    address: '666 Cedar St',
  },
  {
    id: 'id_8',
    name: 'Samantha',
    surname: 'Davis',
    gender: 'female',
    age: 33,
    phone: '123-40-7897',
    email: 'samantha.davis@example.com',
    address: '1001 Fir St',
  },
  {
    id: 'id_9',
    name: 'William',
    surname: 'Moore',
    gender: 'male',
    age: 63,
    phone: '123-456-7898',
    email: 'william.moore@example.com',
    address: '1212 Spruce St',
  },
  {
    id: 'id_10',
    name: 'Laura',
    surname: 'Garcia',
    gender: 'female',
    age: 18,
    phone: '123-456-7899',
    email: 'laura.garcia@example.com',
    address: '4444 Willow St',
  },
]
